### ISSUE TITLE
Applio using Linux & AMD ROCm broken since updated

### ISSUE THREAD

**Issue by UberStorm** [IAHispano/Applio-RVC-Fork#107]
Hi,
since last update Applio is borken for me.
I have two HUGE problems:

1. if the two new training checkboxes are checked, it doesn't work. I get this error:

> FileNotFoundError: [Errno 2] No such file or directory: 'tensorboard --logdir "logs/noakirelv5" --reload_interval 1 --port 7898'

2. Suddenly I get this error and every epoch takes 6 TO 7 MINUTES! before the update it was 1 minute for every epoch!

> /home/maor/.local/lib/python3.10/site-packages/torch/functional.py:660: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
> Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:874.)
>   return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
> /home/maor/.local/lib/python3.10/site-packages/torch/autograd/__init__.py:254: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
> grad.sizes() = [1, 21, 96], strides() = [57120, 96, 1]
> bucket_view.sizes() = [1, 21, 96], strides() = [2016, 96, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:322.)
>   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> INFO:noakirelv5:Saving model and optimizer state at epoch 450 to ./logs/noakirelv5/G_2333333.pth
> INFO:noakirelv5:Saving model and optimizer state at epoch 450 to ./logs/noakirelv5/D_2333333.pth
> INFO:noakirelv5:saving ckpt noakirelv5_e450:Success.
> INFO:noakirelv5:Epoch: 450 [2023-10-31 15:16:02] | **(0:06:57.611943)**

My GPU is RX 6700 XT with ROCm installed, and yes, I do the EXPORT commands before starting Applio so it's not the problem...

**Comment by KawaiianPizza** [comment]
> if the two new training checkboxes are checked, it doesn't work. I get this error:
> FileNotFoundError: [Errno 2] No such file or directory: 'tensorboard --logdir "logs/noakirelv5" --reload_interval 1 --port 7898'

Could you try running `pip install tensorboard` and trying again?

> Suddenly I get this error and every epoch takes 6 TO 7 MINUTES! before the update it was 1 minute for every epoch!

Do you have the full log I could look at?

**Comment by UberStorm** [comment]
> > if the two new training checkboxes are checked, it doesn't work. I get this error:
> > FileNotFoundError: [Errno 2] No such file or directory: 'tensorboard --logdir "logs/noakirelv5" --reload_interval 1 --port 7898'
> 
> Could you try running `pip install tensorboard` and trying again?
> 
> > Suddenly I get this error and every epoch takes 6 TO 7 MINUTES! before the update it was 1 minute for every epoch!
> 
> Do you have the full log I could look at?

about the first issue, I did it few times and also tried to reinstall tensorflow-rocm.
this is the full log:
```
2023-10-31 22:38:23 | INFO | assets.configs.config | Found GPU AMD Radeon RX 6700 XT
is_half:True, device:cuda:0
2023-10-31 22:38:25 | INFO | __main__ | Starting the Flask server
2023-10-31 22:38:25 | INFO | __main__ | Flask server started!
2023-10-31 22:38:25 | INFO | assets.i18n.i18n | Using Language: en_US
2023-10-31 22:38:25 | INFO | lib.tools.loader_themes | Theme Loaded: Applio
Running on local URL:  http://0.0.0.0:7897
2023-10-31 22:38:32 | INFO | httpx | HTTP Request: POST http://localhost:7897/api/predict "HTTP/1.1 200 OK"
2023-10-31 22:38:32 | INFO | httpx | HTTP Request: POST http://localhost:7897/reset "HTTP/1.1 200 OK"
2023-10-31 22:38:33 | INFO | httpx | HTTP Request: POST http://localhost:7897/api/predict "HTTP/1.1 200 OK"
2023-10-31 22:38:33 | INFO | httpx | HTTP Request: POST http://localhost:7897/reset "HTTP/1.1 200 OK"
2023-10-31 22:38:35 | INFO | httpx | HTTP Request: POST http://localhost:7897/api/predict "HTTP/1.1 200 OK"
2023-10-31 22:38:35 | INFO | httpx | HTTP Request: POST http://localhost:7897/reset "HTTP/1.1 200 OK"
2023-10-31 22:38:39 | INFO | httpx | HTTP Request: POST http://localhost:7897/api/predict "HTTP/1.1 200 OK"
2023-10-31 22:38:39 | INFO | __main__ | Use gpus: 0
2023-10-31 22:38:39 | INFO | __main__ | "python" lib/infer/modules/train/train.py -e "noakirel" -sr 48k -f0 1 -bs 18 -g 0 -te 9999 -se 10 -pg assets/pretrained_v2/f0G48k.pth -pd assets/pretrained_v2/f0D48k.pth -l 1 -c 0 -sw 1 -v v2 -rc 1 -sof 1
Traceback (most recent call last):
  File "/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "/home/maor/Documents/Applio-RVC-Fork/infer-web.py", line 1190, in click_train
    TB = Popen(f'tensorboard --logdir "logs/{exp_dir1}" --reload_interval 1 --port {os.environ["TENSORBOARD_PORT"]}', cwd=now_dir)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tensorboard --logdir "logs/noakirel" --reload_interval 1 --port 7898'
2023-10-31 22:38:39 | INFO | httpx | HTTP Request: POST http://localhost:7897/api/predict "HTTP/1.1 500 Internal Server Error"
2023-10-31 22:38:39 | INFO | httpx | HTTP Request: POST http://localhost:7897/reset "HTTP/1.1 200 OK"
2023-10-31 22:38:39 | INFO | httpx | HTTP Request: POST http://localhost:7897/reset "HTTP/1.1 200 OK"

```

about the second issue, this is the full log:
```

INFO:noakirel:Loaded pretrained assets/pretrained_v2/f0G48k.pth
INFO:noakirel:<All keys matched successfully>
INFO:noakirel:Loaded pretrained assets/pretrained_v2/f0D48k.pth
INFO:noakirel:<All keys matched successfully>
INFO:noakirel:View Tensorboard progress at http://localhost:7898/?pinnedCards=%5B%7B%22plugin%22%3A%22scalars%22%2C%22tag%22%3A%22loss%2Fg%2Ftotal%22%7D%2C%7B%22plugin%22%3A%22scalars%22%2C%22tag%22%3A%22loss%2Fd%2Ftotal%22%7D%2C%7B%22plugin%22%3A%22scalars%22%2C%22tag%22%3A%22loss%2Fg%2Fkl%22%7D%2C%7B%22plugin%22%3A%22scalars%22%2C%22tag%22%3A%22loss%2Fg%2Fmel%22%7D%5D&smoothing=0.99
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/torch/functional.py:660: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:874.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/torch/functional.py:660: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:874.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/torch/functional.py:660: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:874.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/torch/functional.py:660: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:874.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
DEBUG:lib.infer.infer_libs.train.mel_processing:max value is tensor(1.0825)
DEBUG:lib.infer.infer_libs.train.mel_processing:max value is tensor(1.0842)
DEBUG:lib.infer.infer_libs.train.mel_processing:min value is tensor(-1.0934)
DEBUG:lib.infer.infer_libs.train.mel_processing:max value is tensor(1.0842)
/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/torch/functional.py:660: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:874.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/torch/autograd/__init__.py:254: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 21, 96], strides() = [57120, 96, 1]
bucket_view.sizes() = [1, 21, 96], strides() = [2016, 96, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:322.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:noakirel:Train Epoch: 1 [0%]
INFO:noakirel:[0, 0.0001]
INFO:noakirel:[loss_disc=3.990] | [loss_gen=2.981] | [loss_fm=15.337] | [loss_mel=43.831] | [loss_kl=9.000]
DEBUG:matplotlib:matplotlib data path: /home/maor/Documents/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/maor/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
INFO:noakirel:Epoch: 1 [2023-10-31 22:46:26] | (0:06:07.315058)

```


![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/147564504/67e86b32-eda7-4dd3-aee0-942e451b53c2)

and this is a picture from NVTOP when I start training:
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/147564504/585f6545-3561-44c4-9b80-d2d99ad6de6c)

 as you can see it definetly uses the GPU memory and the CPU...

**Comment by HyperChocolat** [comment]
to be fair rocm never was supported. it just was there to look nice. anyways let me check this thing

**Comment by KawaiianPizza** [comment]
I'm probably going to rewrite it so it doesn't use tensorboard anymore, hopefully that will resolve multiplatform issues

**Comment by HyperChocolat** [comment]
> I'm probably going to rewrite it so it doesn't use tensorboard anymore, hopefully that will resolve multiplatform issues

nah it can be fixed. just let me check it rq

**Comment by UberStorm** [comment]
After uninstalling the venv created with the newer version & reverting to an earlier version, it works again.
I tried to use the older version with the venv existing on my computer, and it still didn't work. There's something going on with the venv when using Linux & ROCm (v5.7 in my case).
