### ISSUE TITLE
The specified network name is no longer available

### ISSUE THREAD

**Issue by GH0STSecurity** [IAHispano/Applio-RVC-Fork#122]
```
2023-11-11 15:49:33 | INFO | assets.configs.config | Found GPU NVIDIA GeForce GTX 750 Ti
is_half:True, device:cuda:0
Traceback (most recent call last):
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\infer-web.py", line 65, in <module>
    import tabs.tts as tts
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 258, in <module>
    set_edge_voice = get_edge_voice()
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 246, in get_edge_voice
    voices_json = loop.run_until_complete(loop_main())
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 240, in loop_main
    voices = await create()
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 228, in create
    voices = await list_voices() if custom_voices is None else custom_voices
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 204, in list_voices
    async with session.get(
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\client.py", line 560, in _request
    await resp.start(conn)
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 64] The specified network name is no longer available
```
how do i fix this shit, im tired of all codes not working :'( every single rvc i tried is broken ( atleast for me :(( )

**Comment by aitronssesin** [comment]
The code is not broken there's a problem with your network connection what OS are you using?

**Comment by GH0STSecurity** [comment]
> The code is not broken there's a problem with your network connection what OS are you using?

windows

**Comment by aitronssesin** [comment]
Do you have some type of antivirus or firewall apart from windows default?

**Comment by GH0STSecurity** [comment]
> Do you have some type of antivirus or firewall apart from windows default?

nope

**Comment by GH0STSecurity** [comment]
but this time i got this error
```
023-11-11 15:09:13 | INFO | assets.configs.config | Found GPU NVIDIA GeForce GTX 750 Ti
is_half:True, device:cuda:0
2023-11-11 15:10:19 | INFO | __main__ | Starting the Flask server
2023-11-11 15:10:19 | INFO | __main__ | Flask server started!
2023-11-11 15:10:19 | INFO | assets.i18n.i18n | Using Language: en_US
2023-11-11 15:10:19 | INFO | lib.tools.loader_themes | Theme Loaded: Applio
Traceback (most recent call last):
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\lib\tools\server.py", line 1, in <module>
    from flask import Flask, request, Response
ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\gradio\networking.py", line 121, in start_server
    s.bind((LOCALHOST_NAME, server_port))
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\infer-web.py", line 3075, in <module>
    GradioRun(app)
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\infer-web.py", line 3063, in GradioRun
    app.queue(concurrency_count=concurrency_count, max_size=max_size).launch(
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1771, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\gradio\networking.py", line 124, in start_server
    raise OSError(
OSError: Port 7897 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
Press any key to continue . . .
```, i use diffrent ports each times, sometime it doesnt work but im not sure if its because the port is in use

**Comment by aitronssesin** [comment]
That error is because you have opened Applio twice, but the first error is so peculiar because is like the network adapter isn't being detected by aiohttp

**Comment by aitronssesin** [comment]
And flask I think is broken in the runtime but it doesn't make the first error appear

**Comment by GH0STSecurity** [comment]
btw how long does it approximately takes for applio to open? because sometimes it takes like 15 minutes and im not sure whether its stuck or still loading fine

**Comment by GH0STSecurity** [comment]
```
2023-11-11 16:20:03 | INFO | assets.configs.config | Found GPU NVIDIA GeForce GTX 750 Ti
is_half:True, device:cuda:0
Traceback (most recent call last):
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\infer-web.py", line 65, in <module>
    import tabs.tts as tts
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 258, in <module>
    set_edge_voice = get_edge_voice()
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 246, in get_edge_voice
    voices_json = loop.run_until_complete(loop_main())
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 240, in loop_main
    voices = await create()
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 228, in create
    voices = await list_voices() if custom_voices is None else custom_voices
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\tabs\tts.py", line 222, in list_voices
    data = json.loads(await url.text())
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\client_reqrep.py", line 1081, in text
    await self.read()
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\streams.py", line 375, in read
    block = await self.readany()
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\streams.py", line 397, in readany
    await self._wait("readany")
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\streams.py", line 304, in _wait
    await waiter
  File "G:\Artificial_Intelilgence\Applio-RVC-Fork\runtime\lib\site-packages\aiohttp\helpers.py", line 720, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Press any key to continue . . .
``` 
this is the third type of error i just got lol

**Comment by aitronssesin** [comment]
Yep there's something wrong with aiohttp could you try reinstall Applio and install it with the second option called "conda"

**Comment by GH0STSecurity** [comment]
> Yep there's something wrong with aiohttp could you try reinstall Applio and install it with the second option called "conda"

yeah im pretty sure thats not gonna fix anything 😭, already tried like 5 other RVC, idk but for some reason im so unlucky that i can never reach my goal and all codes give me errors, sometime i go as far as even modifiying the code of the library and repositories code with the thought of being able to fix it ._., but yeah theres infinite amount of errors blocking my way lol, anyways thanks man

**Comment by aitronssesin** [comment]
No problem I'm sorry I can't fix your issue

**Comment by GH0STSecurity** [comment]
> Yep there's something wrong with aiohttp could you try reinstall Applio and install it with the second option called "conda"

pretty sure this is not the right the place to ask this but im gonna ask it anyways, by anychance do you know any website that i can generate tts in? perhaps with ability to clone voices or use a trained voice model file?

**Comment by GH0STSecurity** [comment]
cuz i definitely cant run something locally to do it so my only way is online services now

**Comment by aitronssesin** [comment]
you can try eleven labs but I think there's s cap of uses
