### ISSUE TITLE
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer

### ISSUE THREAD

**Issue by hpnyaggerman** [IAHispano/Applio-RVC-Fork#126]
### Issue: Training Process Halts with Errors on Applio

**Environment Specifications:**
- **Operating System:**  Debian GNU/Linux 12 (bookworm) x86_64  6.1.0-9-amd64
- **Python Version:** 3.9.18
- GPU: Dual NVIDIA GeForce RTX 4090s
- Python Environment: Conda virtual environment specifically for Applio

**Steps to Reproduce:**
1. Installed Applio using the official installation script.
2. Went into the Applio's site-packages directory and manually updated PyTorch from version 2.0.0 to 2.1.0. This was necessary to support CUDA version 11.8, which is required by my graphics cards.
3. Launched Applio and uploaded my dataset to the specified folder.
4. Navigated to the training tab, performed preprocessing, and then feature extraction.
5. Started the training process.

**Issue Encountered:**
During training, I encountered a series of errors, causing the training process to halt. The detailed error log is as follows:
```
Process Process-2:
Traceback (most recent call last):
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/lib/infer/modules/train/train.py", line 280, in run
    utils.latest_checkpoint_path(hps.model_dir, "D_*.pth"), net_d, optim_d
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/lib/infer/infer_libs/train/utils.py", line 212, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hkyouma/miniconda3/envs/voicegen/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hkyouma/miniconda3/envs/voicegen/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/lib/infer/modules/train/train.py", line 317, in run
    logger.info(
UnboundLocalError: local variable 'logger' referenced before assignment
INFO:modeltraining:Loaded pretrained assets/pretrained_v2/f0G48k.pth
INFO:modeltraining:<All keys matched successfully>
INFO:modeltraining:Loaded pretrained assets/pretrained_v2/f0D48k.pth
INFO:modeltraining:<All keys matched successfully>
/home/hkyouma/ai/voicegen/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/hkyouma/ai/voicegen/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/hkyouma/ai/voicegen/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/hkyouma/ai/voicegen/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/hkyouma/ai/voicegen/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:863.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
Process Process-1:
Traceback (most recent call last):
  File "/home/hkyouma/miniconda3/envs/voicegen/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hkyouma/miniconda3/envs/voicegen/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/lib/infer/modules/train/train.py", line 359, in run
    train_and_evaluate(
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/lib/infer/modules/train/train.py", line 572, in train_and_evaluate
    scaler.scale(loss_disc).backward()
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/hkyouma/ai/voicegen/Applio-RVC-Fork/.venv/lib/python3.9/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [127.0.0.1]:53406
```

**Observations and Concerns:**
- The `IndexError` in `train.py` suggests an issue with the checkpoint loading process.
- An `UnboundLocalError` followed, hinting at a problem in the exception handling mechanism.
- The application is using deprecated features of PyTorch (`stft` with `return_complex=False`), raising concerns about compatibility with newer versions of PyTorch.
- A `RuntimeError` related to Gloo indicates a potential issue in the network communication setup.

I suspect these issues might be related to the PyTorch version upgrade I performed. However, this upgrade was essential for compatibility with my hardware setup.

Any assistance or guidance on resolving these errors would be greatly appreciated.

**Comment by hpnyaggerman** [comment]
I'd appreciate any input on the issue whatsoever.

**Comment by hpnyaggerman** [comment]
Perhaps an important addition. This error does not appear during inference. In fact, inference goes just fine.

**Comment by Aldair502** [comment]
don't use 3.9 on linux. use 3.11 it says it in the readme

**Comment by AdverseMiller** [comment]
I'm getting this issue as well, it ONLY happens when I have both GPUs selected, otherwise the issue disappears
