### ISSUE TITLE
How to fix FileNotFoundError: [Errno 2] No such file or directory: 'assets\\audios\\audio-outputs\\SampleName_merged.wav' &

### ISSUE THREAD

**Issue by IvanFromGardarike** [IAHispano/Applio-RVC-Fork#131]
A code error pops up when I use Split Audio (Better Results).
How to fix it?

I have already reinstalled and added to PATH but the result is the same.

> Ignore the warning if you saw any...
> Segment 0 created!
> Segment 1 created!
> Segment 2 created!
> Total segments created: 3
> Split all chunks for assets\audios\Кипелов_Не для меня_9db.wav successfully!
> Finish
> ------
> assets\audios\Кипелов_Не_для_меня_9db
> ['assets\\audios\\Кипелов_Не_для_меня_9db\\chunk0.wav', 'assets\\audios\\Кипелов_Не_для_меня_9db\\chunk1.wav', 'assets\\audios\\Кипелов_Не_для_меня_9db\\chunk2.wav']
> 
> Starting inference for 'chunk0.wav'
> Attempting to load assets\audios\Кипелов_Не_для_меня_9db\chunk0.wav....
> Processing: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.53s/window]
> Returning completed audio...
> 
> Starting inference for 'chunk1.wav'
> Attempting to load assets\audios\Кипелов_Не_для_меня_9db\chunk1.wav....
> Processing: 0window [00:00, ?window/s]
> Returning completed audio...
> 
> Starting inference for 'chunk2.wav'
> Attempting to load assets\audios\Кипелов_Не_для_меня_9db\chunk2.wav....
> Processing: 0window [00:00, ?window/s]
> Returning completed audio...
> Finished processing segmented audio, now merging audio...
> assets\audios
> Кипелов_Не для меня_9db
> An error occurred: [Errno 2] No such file or directory: 'assets\\audios\\Кипелов_Не для меня_9db_timestamps.txt'
> Traceback (most recent call last):
>   File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
>     output = await app.get_blocks().process_api(
>   File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1349, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
>     prediction_value = block.postprocess(prediction_value)
>   File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 2591, in postprocess
>     file_path = self.make_temp_copy_if_needed(y)
>   File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 259, in make_temp_copy_if_needed
>     temp_dir = self.hash_file(file_path)
>   File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 223, in hash_file
>     with open(file_path, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'assets\\audios\\audio-outputs\\Кипелов_Не для меня_9db_merged.wav'

**Comment by IvanFromGardarike** [comment]
Edit: It worked fine at first, but now it's not working at all. :(

**Comment by freyzamarshall02** [comment]
same

**Comment by TheUserNil** [comment]
A sorry https://github.com/IAHispano/Applio-RVC-Fork/commit/bda8bce731db85639f5e554be342ecffef1dc8db

> A code error pops up when I use Split Audio (Better Results). How to fix it?
> 
> I have already reinstalled and added to PATH but the result is the same.
> 
> > ## Ignore the warning if you saw any...
> > Segment 0 created!
> > Segment 1 created!
> > Segment 2 created!
> > Total segments created: 3
> > Split all chunks for assets\audios\Кипелов_Не для меня_9db.wav successfully!
> > Finish
> > assets\audios\Кипелов_Не_для_меня_9db
> > ['assets\audios\Кипелов_Не_для_меня_9db\chunk0.wav', 'assets\audios\Кипелов_Не_для_меня_9db\chunk1.wav', 'assets\audios\Кипелов_Не_для_меня_9db\chunk2.wav']
> > Starting inference for 'chunk0.wav'
> > Attempting to load assets\audios\Кипелов_Не_для_меня_9db\chunk0.wav....
> > Processing: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.53s/window]
> > Returning completed audio...
> > Starting inference for 'chunk1.wav'
> > Attempting to load assets\audios\Кипелов_Не_для_меня_9db\chunk1.wav....
> > Processing: 0window [00:00, ?window/s]
> > Returning completed audio...
> > Starting inference for 'chunk2.wav'
> > Attempting to load assets\audios\Кипелов_Не_для_меня_9db\chunk2.wav....
> > Processing: 0window [00:00, ?window/s]
> > Returning completed audio...
> > Finished processing segmented audio, now merging audio...
> > assets\audios
> > Кипелов_Не для меня_9db
> > An error occurred: [Errno 2] No such file or directory: 'assets\audios\Кипелов_Не для меня_9db_timestamps.txt'
> > Traceback (most recent call last):
> > File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
> > output = await app.get_blocks().process_api(
> > File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1349, in process_api
> > data = self.postprocess_data(fn_index, result["prediction"], state)
> > File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
> > prediction_value = block.postprocess(prediction_value)
> > File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 2591, in postprocess
> > file_path = self.make_temp_copy_if_needed(y)
> > File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 259, in make_temp_copy_if_needed
> > temp_dir = self.hash_file(file_path)
> > File "F:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 223, in hash_file
> > with open(file_path, "rb") as f:
> > FileNotFoundError: [Errno 2] No such file or directory: 'assets\audios\audio-outputs\Кипелов_Не для меня_9db_merged.wav'

Try https://github.com/IAHispano/Applio-RVC-Fork/commit/bda8bce731db85639f5e554be342ecffef1dc8db
