### ISSUE TITLE
Error when formanting

### ISSUE THREAD

**Issue by Rudy34160** [IAHispano/Applio-RVC-Fork#154]
When I want to use the "Quefrency for formant shifting" and "Timbre for formant shifting" parameters, I receive the following error message:

Processing: 0window [00:00, ?window/s]
Returning completed audio...
💾 Generated audio saved to: assets/audios/audio-outputs\generated_audio_8.wav
2023-11-29 15:35:41 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant

Anyone have a solution to this problem?

**Comment by blaise-tk** [comment]
Try replicating the issue with the last version of Applio

**Comment by Rudy34160** [comment]
> Try replicating the issue with the last version of Applio

OK
I'm finishing training and will do the test again by upgrading version 2.1.4 to version 2.0.0, crossing my fingers that it works! 😉

**Comment by blaise-tk** [comment]
If is not fixed, let me know and we will fix it.
