### ISSUE TITLE
Can't run ./go-applio.sh on Arch Linux

### ISSUE THREAD

**Issue by Vamaka12** [IAHispano/Applio-RVC-Fork#156]
## Environment
- OS: Arch Linux
- Kernel: 6.6.3
- Python Version: 3.11.6
- Hardware:
- Intel i7-8750H
- NVIDIA GTX 1060 6GB
- 24 GB RAM

## Issue Description:
When I try to run ./go-applio.sh, it downloads huggingface models and then it gives the following error:

```
Traceback (most recent call last):
  File "/home/vam/Desktop/rvc/Applio-RVC-Fork/infer-web.py", line 26, in <module>
    import fairseq
  File "/home/vam/Desktop/rvc/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/vam/Desktop/rvc/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/vam/Desktop/rvc/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/vam/Desktop/rvc/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/vam/Desktop/rvc/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
Press Enter to continue...
```

Also ./install_Applio-linux.sh at somepoint gives dependency conflict for numpy:
```
INFO: pip is looking at multiple versions of onnxruntime-gpu to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r assets/requirements/requirements.txt (line 11), -r assets/requirements/requirements.txt (line 2), -r assets/requirements/requirements.txt (line 20), -r assets/requirements/requirements.txt (line 7), -r assets/requirements/requirements.txt (line 8) and numpy==1.23.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.23.5
    fairseq 0.12.2 depends on numpy; python_version >= "3.7"
    gradio 3.34.0 depends on numpy
    librosa 0.9.1 depends on numpy>=1.17.0
    matplotlib 3.7.2 depends on numpy>=1.20
    onnxruntime-gpu 1.15.1 depends on numpy>=1.24.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: Skipping torch as it is not installed.
WARNING: Skipping torchvision as it is not installed.
WARNING: Skipping torchaudio as it is not installed.
Looking in indexes: https://download.pytorch.org/whl/cu117
Collecting torch==2.0.0
.....
```
after some time it installs newer numpy:

```
Installing collected packages: flatbuffers, protobuf, numpy, humanfriendly, coloredlogs, onnxruntime
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.1
    Uninstalling numpy-1.24.1:
      Successfully uninstalled numpy-1.24.1
Successfully installed coloredlogs-15.0.1 flatbuffers-23.5.26 humanfriendly-10.0 numpy-1.26.2 onnxruntime-1.16.3 protobuf-4.25.1

```
I also had same issue as #153 (tqdm not being installed automatically)
`pip install tqdm` solved it, and now everytime I delete entire Apllio-RVC-Fork folder and reinstall everything, it gets installed by itself?

## Attempted solutions
- Removed numpy version in assets/requirements/requirements.txt
- Tried:
```
git clone https://github.com/IAHispano/Applio-RVC-Fork && cd Applio-RVC-Fork
chmod +x install_Applio.sh && ./install_Applio.sh
```
instead of
```
wget https://github.com/IAHispano/Applio-RVC-Fork/releases/download/v2.0.0/install_Applio-linux.sh
chmod +x install_Applio-linux.sh && ./install_Applio-linux.sh
```

**Comment by Vamaka12** [comment]
Got it working with python 3.9.18
You should update your readme guys:

https://github.com/IAHispano/Applio-RVC-Fork/blob/95e947a7b36384022b00f406460b2b429b22ff24/README.md?plain=1#L128

**Comment by Vamaka12** [comment]
Just checked, it also works with 3.10.13

**Comment by prism2001** [comment]
i am running into this exact error despite having all those packages installed

**Comment by Aldair502** [comment]
> i am running into this exact error despite having all those packages installed

Yeh since i deleted my repos there isn't python 11 support. the python 11 support fixes dependencies like farseq and numpy
