### ISSUE TITLE
error al intentar iniciar webui

### ISSUE THREAD

**Issue by Pocholo95** [IAHispano/Applio-RVC-Fork#16]
Starting Applio...

Traceback (most recent call last):
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "socket.py", line 954, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002665D5B97C0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pastebin.com', port=443): Max retries exceeded with url: /raw/mpH4hRcF (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002665D5B97C0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Applio-RVC-Fork-Recode\infer-web.py", line 14, in <module>
    from mdx_processing_script import get_model_list,id_to_ptm,prepare_mdx,run_mdx
  File "E:\Applio-RVC-Fork-Recode\mdx_processing_script.py", line 28, in <module>
    stem_naming = requests.get(stem_naming).json()
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Applio-RVC-Fork-Recode\runtime\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pastebin.com', port=443): Max retries exceeded with url: /raw/mpH4hRcF (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002665D5B97C0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
Presione una tecla para continuar . . .

**Comment by blaise-tk** [comment]
Si necesitas ayuda, comentalo en el servidor de Discord de soporte.

https://discord.gg/IAHispano
