### ISSUE TITLE
BUG: UVR5 doesn't work. 

### ISSUE THREAD

**Issue by company8** [IAHispano/Applio-RVC-Fork#163]
## Environment
- OS: Linux - Google Colab
- Python Version: 3.10.12
- Hardware: T4 GPU

## Issue Description:

UVR5 is either stuck on "Starting audio conversion..." and no progress in terminal or :
Starting audio conversion... (This might take a moment) Traceback (most recent call last):   File "/content/Applio-RVC-Fork/infer-web.py", line 434, in uvr     os.path.join(os.environ["tmp"]),   File "/usr/lib/python3.10/os.py", line 680, in __getitem__     raise KeyError(key) from None KeyError: 'tmp'

## Attempted solutions

Whether the path to the audio file is specified or not it doesn't work, with specified path the "Starting audio conversion" but nothing in terminal happens. If you put the audio file in /assets/audio but don't specify the path of the audio file it will throw the "KeyError". It's a 20 second audio clip, it shouldn't take long on CPU or GPU. Another thing even if you upload the file from the gradio link it gets stuck in the "Starting audio conversion" and no progress. Running the infer python script over and reinstalling didn't work. Please fix the UVR5 or give me some solution, thank you :)

**Comment by company8** [comment]
Update: UVR5 VR models works if you upload them via the gradio interface but not from the notebook locally.

**Comment by company8** [comment]
UPDATE: Workarounds in COLAB for using UVR5.

Here are some tips/solutions that I found:

Sample rate: If your audio is 48khz, it won't work. 44.1khz works, so you need to resample all of your dataset to 44.1khz in order to work. I am certain of this because same audio in 48khz, UVR doesn't work. 44.1khz works just fine.

Name of audio: This I believe is also a issue, I found that using just letters it has no issue but if you audio is starting I think with CAPITAL letters it doesn't "recognize" it ? I am not certain about this.

Opinion: I don't know if this is because of the code inside this repo (I found in the code "44.1khz") but I don't know. Or this is simply a Google Colab issue. The "solutions" work for UVR VR DeEcho-DeReverb by FoxJoy which is I think the most used model and is needed. That's all, thank you for coming to my TED Talk.
