### ISSUE TITLE
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

### ISSUE THREAD

**Issue by alvar036** [IAHispano/Applio-RVC-Fork#176]
## Environment
- OS: Ventura 13.3
- Python Version: Python 3.9.6 (default, May  7 2023, 23:32:44) 
- Hardware: Apple Silicon M2

When running sh ./go-applio.sh and then selecting [1] NVDIDIA/AMD this happens:

## Issue Description:
Traceback (most recent call last):
  File "/Users/alvarom2/Documents/RVC/applio/Applio-RVC-Fork/infer-web.py", line 26, in <module>
    import fairseq
  File "/Users/alvarom2/Documents/RVC/applio/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/Users/alvarom2/Documents/RVC/applio/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/Users/alvarom2/Documents/RVC/applio/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/Users/alvarom2/Documents/RVC/applio/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/Users/alvarom2/Documents/RVC/applio/Applio-RVC-Fork/.venv/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
Press Enter to continue...

**Comment by blaise-tk** [comment]
We do not have MacOS equipment so we cannot fully determine a solution for your error.

**Comment by alvar036** [comment]
> We do not have MacOS equipment so we cannot fully determine a solution for your error.

yeah i figured, still wanted to post it though. Might be someone who found a fix for it.

**Comment by AdverseMiller** [comment]
Downgrade to 3.9

**Comment by 39sdev** [comment]
> Downgrade to 3.9

do you have the command on hand? ain't familiar with venv
