### ISSUE TITLE
Missing Tensorboard

### ISSUE THREAD

**Issue by molotovah** [IAHispano/Applio-RVC-Fork#40]
On the latest release, tensorboard is missing.

**Comment by aitronssesin** [comment]
We already updated the tennsorboard use the applio manager to update + dependencies and start the tensorboard with go-tensorboard

**Comment by molotovah** [comment]
`F:\Downloads\Applio-RVC-Fork>python lib/fixes/tensor-launch.py
Traceback (most recent call last):
  File "F:\Downloads\Applio-RVC-Fork\lib\fixes\tensor-launch.py", line 11, in <module>
    url = tb.launch()
  File "C:\Users\defol\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboard\program.py", line 316, in launch
    server = self._make_server()
  File "C:\Users\defol\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboard\program.py", line 467, in _make_server
    app = application.TensorBoardWSGIApp(
  File "C:\Users\defol\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboard\backend\application.py", line 139, in TensorBoardWSGIApp
    return TensorBoardWSGI(
  File "C:\Users\defol\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorboard\backend\application.py", line 252, in __init__
    raise ValueError(
ValueError: Duplicate plugins for name projector`

**Comment by molotovah** [comment]
WARNING: The candidate selected for download or install is a yanked version: 'tensorboardx' candidate (version 2.6.2.1 at https://files.pythonhosted.org/packages/f7/94/63570a1a408077217ed086056bcaf5a50c20fcb26b50152ed59e55ec5cab/tensorboardX-2.6.2.1-py2.py3-none-any.whl#sha256=391ee8dc123e5c19c5a565d36e1fe98ddc9f727e1fd71f3e076658e6228ca36d (from https://pypi.org/simple/tensorboardx/))
Reason for being yanked: v2.6.2.1 was released with incorrect commit

**Comment by molotovah** [comment]
I had 2 tensorboard installed, i managed to solved the problem running : 

```
pip uninstall tb-nightly tensorboardX tensorboard
pip install tensorboard
```

**Comment by aitronssesin** [comment]
The same thing does the manager

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-RVC-Fork/assets/74368135/4841ecfc-0bb4-4ba0-a1f6-e1e58fc12c87)
