### ISSUE TITLE
cannot do inference or train in directml

### ISSUE THREAD

**Issue by T713** [IAHispano/Applio-RVC-Fork#51]
I have been trying to make inferences or training to test my RX 590 but I always end up receiving errors, for example when making inferences having started applio with the option "Start Applio with Runtime (AMD Support)" (since if I start it with the option "Start Applio (AMD Support)" never loads) gives me the error:

Attempting to load assets\audios\1_YOASOBI Yoru ni Kakeru - Cover in Spanish 320 kbps_Vocals.wav....
2023-09-23 22:41:38 | WARNING | lib.infer.modules.vc.modules | Traceback (most recent call last):
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\modules\vc\modules.py", line 254, in vc_single
     audio_opt = self.pipeline.pipeline(
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\modules\vc\pipeline.py", line 594, in pipeline
     pitch, pitchf = self.get_f0(
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\modules\vc\pipeline.py", line 354, in get_f0
     f0 = self.f0_method_dict[f0_method](**params)
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\modules\vc\pipeline.py", line 260, in get_pitch_dependent_rmvpe
     return self.model_rmvpe.infer_from_audio_with_pitch(x, thred=0.03, f0_min=f0_min, f0_max=f0_max)
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\infer_libs\rmvpe.py", line 662, in infer_from_audio_with_pitch
     hidden = hidden.squeeze(0).cpu().numpy()
AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

Traceback (most recent call last):
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
     output = await app.get_blocks().process_api(
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1349, in process_api
     data = self.postprocess_data(fn_index, result["prediction"], state)
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
     prediction_value = block.postprocess(prediction_value)
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 2586, in postprocess
     file_path = self.audio_to_temp_file(
   File "G:\Applio-RVC-Fork\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
     temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by blaise-tk** [comment]
It should be fixed if not already, in the next update. However if the problem persists do not hesitate to communicate it through the Discord server!
