### ISSUE TITLE
Training Tuple error

### ISSUE THREAD

**Issue by ccateni** [IAHispano/Applio-RVC-Fork#67]
When training, this error shows up.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\ccateni\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\ccateni\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "F:\downloads\Apollov2\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\modules\train\train.py", line 327, in run
    train_and_evaluate(
  File "F:\downloads\Apollov2\Applio-RVC-Fork\Applio-RVC-Fork\lib\infer\modules\train\train.py", line 702, in train_and_evaluate
    info.append("Epoch: {} {}".format(epoch, epoch_recorder.record()))
AttributeError: 'tuple' object has no attribute 'append'

**Comment by ccateni** [comment]
appears to only show up when using "Cache all training sets to GPU memory. Caching small datasets (less than 10 minutes) can speed up training"

**Comment by TheUserNil** [comment]
Update applio
