### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.globals'

### ISSUE THREAD

**Issue by udalipzh** [IAHispano/Applio-RVC-Fork#87]
I downloaded runtime by [install_Applio-windows.bat](https://github.com/IAHispano/Applio-RVC-Fork/releases/download/v2.0.0/install_Applio-windows.bat) and try to run applio with runtime, but an error occurs when importing a local file, it exists and has content, I checked. I tried reinstalling python (by installing a different version: 3.9.8, 3.10) - it didn't help.

```
Starting Applio with runtime for Nvidia support (you must have it installed)...
Traceback (most recent call last):
  File "D:\Applio-RVC-Fork\infer-web.py", line 12, in <module>
    import lib.globals.globals as rvc_globals
ModuleNotFoundError: No module named 'lib.globals'
```

**Comment by bygimenez** [comment]
> I downloaded runtime by [install_Applio-windows.bat](https://github.com/IAHispano/Applio-RVC-Fork/releases/download/v2.0.0/install_Applio-windows.bat) and try to run applio with runtime, but an error occurs when importing a local file, it exists and has content, I checked. I tried reinstalling python (by installing a different version: 3.9.8, 3.10) - it didn't help.
> 
> ```
> Starting Applio with runtime for Nvidia support (you must have it installed)...
> Traceback (most recent call last):
>   File "D:\Applio-RVC-Fork\infer-web.py", line 12, in <module>
>     import lib.globals.globals as rvc_globals
> ModuleNotFoundError: No module named 'lib.globals'
> ```

https://docs.applio.org/faq/no-module/

**Comment by udalipzh** [comment]
> > I downloaded runtime by [install_Applio-windows.bat](https://github.com/IAHispano/Applio-RVC-Fork/releases/download/v2.0.0/install_Applio-windows.bat) and try to run applio with runtime, but an error occurs when importing a local file, it exists and has content, I checked. I tried reinstalling python (by installing a different version: 3.9.8, 3.10) - it didn't help.
> > ```
> > Starting Applio with runtime for Nvidia support (you must have it installed)...
> > Traceback (most recent call last):
> >   File "D:\Applio-RVC-Fork\infer-web.py", line 12, in <module>
> >     import lib.globals.globals as rvc_globals
> > ModuleNotFoundError: No module named 'lib.globals'
> > ```
> 
> https://docs.applio.org/faq/no-module/

as I said, the error is when importing a local runtime file, not PIP package.
