### ISSUE TITLE
Error while running inference: _pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by gaiaml** [IAHispano/Applio-RVC-Fork#88]
Hello,

I'm having this issue while trying to do an inference. (same model and audio works fine on RVC v2).

any idea?

2023-10-11 21:50:32 | INFO | lib.infer.modules.vc.modules | Loading...
2023-10-11 21:50:34 | INFO | lib.infer.modules.vc.modules | Select index: logs\1_angele400_v1\added_IVF848_Flat_nprobe_1_angele400_v1.index
Running on local URL:  http://0.0.0.0:7897

Starting inference for 'Original_vocals2.wav'
Attempting to load assets/audios\Original_vocals2.wav....
2023-10-11 21:50:48 | WARNING | lib.infer.modules.vc.modules | Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\lib\infer\modules\vc\modules.py", line 352, in vc_single
    self.hubert_model = load_hubert(self.config)
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\lib\infer\modules\vc\utils.py", line 32, in load_hubert
    models, _, _ = checkpoint_utils.load_model_ensemble_and_task(
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\runtime\lib\site-packages\fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\runtime\lib\site-packages\fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\runtime\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\runtime\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "C:\Users\Admin\Downloads\Applio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'

**Comment by gaiaml** [comment]
Problem solved, I had to re-download hubert model
